name: notes_app_mobile
description: A Flutter notes application with PDF support and in-app purchases
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  
  # In-App Purchases
  in_app_purchase: ^3.1.11
  
  # Security & Storage
  flutter_secure_storage: ^9.0.0
  
  # HTTP Client
  dio: ^5.3.2
  
  # PDF Handling
  pdfx: ^2.4.0
  flutter_pdfview: ^1.3.2
  
  # UI & Utilities
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Testing
  integration_test:
    sdk: flutter
  
  # Code Generation
  riverpod_generator: ^2.3.4
  build_runner: ^2.4.7
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
